server:
    port: 8081
    context-path: /

spring:
    application:
        name: Notificacao
    mail:
        from: eng.rodrigo.ribeiro.alves@gmail.com
        host: ${EMAIL_SERVER_URL:smtp.gmail.com}
        port: ${EMAIL_SERVER_PORT_PORT:587}
        username: eng.rodrigo.ribeiro.alves@gmail.com
        password: kib&1992
        properties:
            mail:
                transport:
                    protocol: smtp
                smtp:
                    auth: ${EMAIL_SERVER_SMTP_AUTH:true}
                    starttls.enable: ${EMAIL_SERVER_SMTP_STARTTLS:true}
                    starttls.required: ${EMAIL_SERVER_SMTP_STARTTLS:true}
                    ssl.enable: false
                debug: ${EMAIL_SERVER_DEBUG:true}
                test-connection: true
