server:
    port: 8081
    context-path: /

spring:
    application:
        name: Notificacao
    mail:
        from: exemplo@gmail.com
        host: smtp.gmail.com
        port: 587
        username: teste
        password: teste
        properties:
            mail:
                transport:
                    protocol: smtp
                smtp:
                    auth: true
                    starttls.enable: true
                    starttls.required: true
                    ssl.enable: false
                debug: true
                test-connection: true
